---
# tasks file for webserver
- name: install nginx
  apt: 
    name: nginx 
    state: present

- name: Ensure index.html
  copy: src=index.html dest={{dest_folder}}/index.html mode=0555
  notify:
   - restart nginx

