---
# tasks file for prod
- name: Install default-jdk
  apt:
      name: default-jdk
      state: present

- name: Install tomcat
  apt:
      name: tomcat8
      state: present

- name: Copy war int tomcat serv
  synchronize:
    mode: pull
    src:  /home/Project/target/hello-1.0.war
    dest: /var/lib/tomcat8/webapps/hello.war
  delegate_to: devslave1