---
# tasks file for prod
- name: Install default-jdk
  apt:
      name: default-jdk
      state: present

- name: Install tomcat
  apt:
      name: tomcat8
      state: present

- name: Copy war int tomcat serv
  synchronize:
    src:  /home/Project/target
    dest: /var/lib/tomcat8/webapps
  delegate_to: devslave1