FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install maven git tomcat8 default-jdk -y
RUN mkdir /home/Project
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git /home/Project
RUN mvn package -f /home/Project/pom.xml
RUN cp /home/Project/target/hello-1.0.war /var/lib/tomcat8/webapps/hello.war
EXPOSE 8080
CMD ["/usr/lib/systemd/system/tomcat.service", "run"]
