FROM ubuntu:18.04
ENV TOMCAT_MAJOR=8 \
    TOMCAT_VERSION=8.5.37 \
    CATALINA_HOME=/opt/tomcat
RUN mkdir -p /opt
RUN apt-get update
RUN apt-get install maven git curl unzip default-jdk -y
RUN mkdir /home/Project
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git /home/Project
RUN mvn package -f /home/Project/pom.xml
RUN curl -jkSL -o /tmp/apache-tomcat.tar.gz http://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz && \
    gunzip /tmp/apache-tomcat.tar.gz && \
    tar -C /opt -xf /tmp/apache-tomcat.tar && \
    ln -s /opt/apache-tomcat-$TOMCAT_VERSION $CATALINA_HOME
RUN apk del curl && \
    rm -rf /tmp/* /var/cache/apk/*
RUN cp /home/Project/target/hello-1.0.war /var/lib/tomcat8/webapps/hello.war
EXPOSE 8080
COPY startup.sh /opt/startup.sh
ENTRYPOINT /opt/startup.sh
WORKDIR $CATALINA_HOME
