---
- name: Install Maven
  hosts: maven
  become: yes

  tasks:
    - name: Install Maven
      apt:
        name: maven
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name : Create Directory /home/Project
      file:
        path: /home/Project
        state: directory

    - name: Git Clone
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /home/Project
        clone: yes

    - name: Maven Build
      shell: mvn package -f /home/Project/pom.xml

    - name: Copy project in master
      fetch:
        src: /home/Project/target/hello-1.0.war
        dest: /home/
        flat: yes

- name: Install tomcat
  hosts: tomcat
  become: yes

  tasks:
    - name: Install default-jdk
      apt:
        name: default-jdk
        state: present

    - name: Install tomcat
      apt:
        name: tomcat8
        state: present

    - name: Ensure tomcat service started
      service:
        name: tomcat8
        state: started

    - name: Copy war int tomcat serv
      copy:
        src: /home/hello-1.0.war
        dest: /var/lib/tomcat8/webapps/hello.war