---
- name: Install Maven
  hosts: maven
  become: yes

  tasks:
    - name: Install Maven
      apt:
        name: maven
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name : Create Directory /home/Project
      file:
        path: /home/Project
        state: directory

    - name: Git Clone
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /home/Project
        clone: yes

    - name: Maven Build
      shell: mvn package -f /home/Project/pom.xml

- name: Install tomcat
  hosts: tomcat
  become: yes

  tasks:
    - name: Install tomcat
      apt:
        name: tomcat
        state: present

    -name: Ensure tomcat service started
      service:
        name: tomcat
        state: started