- name: add server user
  user:
   name: {{item}}
   groups: "wheel"
   state: present
  with_items:
   - user1
   - user2
   - user3

- name: install mane packages
  apt: name={{item}} state=instelled
  with_items:
    - nginx
    - python3
