version: '3.8'
services:
  maven:
    build: maven
    volumes:
    - type: volume
        source: project
        target: /home/Project/target

  image: tomcat:8.5-jre8
    ports:
      - "80:8080"
    volumes:
      - type: volume
          source: project
          target: /webapps

  volumes:
    project:
      driver: local