version: '3.7'
services:
  maven:
    build: maven
    volumes:
      - project:/home/Project/target

  image: tomcat:8.5-jre8
    ports:
      - "81:8080"
    volumes:
      - project:/webapps
  volumes:
    project:
      driver: local
